apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <h1>Welcome! Amith Website This is a Stateless Nginx Deployment</h1>
    <p>Pod replacement will not affect this page thank you.</p>

