apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateless-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stateless-nginx
  template:
    metadata:
      labels:
        app: stateless-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

        volumeMounts:
        - name: nginx-html-volume
          mountPath: /usr/share/nginx/html

      volumes:
      - name: nginx-html-volume
        configMap:
          name: nginx-html

