apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-lb-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-lb-nginx
  template:
    metadata:
      labels:
        app: demo-lb-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

